espn_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ggjmket-vqb12267
      user: airflow_espn_named
      password: AirflowEspnPassword123
      role: ACCOUNTADMIN
      warehouse: ESPN_WH
      database: API_DATA_DB
      schema: MODELS
      threads: 4
      client_session_keep_alive: true
