services:
  airflow-init:
    image: apache/airflow:2.9.3-python3.11
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./airflow/keys:/opt/airflow/airflow/keys
      - ../espn_etl:/opt/airflow/espn_etl
      - ../espn_dbt:/opt/airflow/espn_dbt
      - airflow-sqlite:/opt/airflow
    command: >
      bash -lc "airflow db migrate &&
      airflow users create --username ${_AIRFLOW_WWW_USER_USERNAME:-airflow} --password ${_AIRFLOW_WWW_USER_PASSWORD:-airflow} --firstname A --lastname U --role Admin --email a@u.com || true"


  airflow:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: airflow-with-dbt:latest
    depends_on: [airflow-init]
    ports: ["8080:8080"]
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - PYTHONPATH=/opt/airflow
      - DBT_PROJECT_DIR=/opt/airflow/espn_dbt
    env_file:
      - ../.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./airflow/keys:/opt/airflow/airflow/keys
      - ../espn_etl:/opt/airflow/espn_etl
      - ../espn_dbt:/opt/airflow/espn_dbt
      - airflow-sqlite:/opt/airflow
    command: >
      bash -lc "airflow webserver -p 8080 & airflow scheduler"

volumes:
  airflow-sqlite:

