services:
  airflow:
    image: apache/airflow:2.9.3-python3.11
    ports: ["8080:8080"]
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - PYTHONPATH=/opt/airflow
      - DBT_PROJECT_DIR=/opt/airflow/espn_dbt
    env_file:
      - .env   
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../espn_etl:/opt/airflow/espn_etl
      - ../espn_dbt:/opt/airflow/espn_dbt
    command: >
      bash -lc "
        airflow db init &&
        airflow users create \
          --username ${_AIRFLOW_WWW_USER_USERNAME:-airflow} \
          --password ${_AIRFLOW_WWW_USER_PASSWORD:-airflow} \
          --firstname A --lastname U --role Admin --email a@u.com || true &&
        airflow webserver -p 8080 &
        airflow scheduler
      "
